apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: odo-devtools
  labels:
    app: odo-devtools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odo-devtools
subjects:
  - kind: ServiceAccount
    name: odo-devtools-service-account